name: '[Workflow] On Documentation Change'

on:
  push:
    paths:
      - 'docs/techdocs/**'
      - '.github/workflows/on_docs_change.yml'
  workflow_dispatch:
    inputs:
      source-dir:
        type: string
        description: 'The directory containing the techdocs files'
        required: false
        default: 'docs/techdocs'

jobs:
  generate-techdocs:
    name: 'Generate TechDocs'
    uses: webgrip/workflows/.github/workflows/techdocs-generate.yml@main
    with:
      source-dir: ${{ github.event.inputs.source-dir || 'docs/techdocs' }}

  github-pages-deploy:
    needs: generate-techdocs
    if: >
      'refs/heads/main' == ${{ github.ref }}
    name: 'Deploy to GitHub Pages'
    uses: webgrip/workflows/.github/workflows/techdocs-deploy-gh-pages.yml@main
